config/routes.rb
Rails.application.routes.draw do

  root to: "posts#index"
  resources :posts do
    resources :comments
  end
  resources :authors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :comments
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :posts


  def self.persisted
    reject { |comment| comment.new_record? }
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :set_post

  def create
    @comment = @post.comments.build(comment_params)

    if @comment.save
      ActionCable.server.broadcast "comments",
                                   render(partial: 'comments/comment', object: @comment)
      flash[:notice] = "Comment has been created"
    else
      flash[:alert] = "Comment has not been created"
    end
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :author_id, :removed)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "Post has been created"
      redirect_to posts_path
    else
      flash[:danger] = "Post has not been created"
      render :new
    end
  end

  def show
    @comment = @post.comments.build
    @comments = @post.comments
  end

  def edit

  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post has been updated"
      redirect_to @post
    else
      flash[:danger] = "Post has not been updated"
      render :edit
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = "Post has been deleted"
      redirect_to posts_path
    end
  end


  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :published_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment-body">
  <%= comment.body %>
</div>
<div class="comment-time">
  <%= time_ago_in_words(comment.created_at) %>
  ago by <%= comment.author.first_name %>
</div>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecruitTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for(@post, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <% if @post.errors.any? %>
        <div class="panel panel-danger col-md-offset-1">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(@post.errors.count, 'error') %>
              prohibited this article from being saved:
            </h2>

            <div class="panel-body">
              <ul>
                <% @post.errors.full_messages.each do |msg| %>
                  <li>
                    <%= msg %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
      <div class="form-group">
        <div class="control-label col-md-1">
          <%= f.label :title %>
        </div>
        <div class="col-md-10">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-1">
          <%= f.label :body %>
        </div>
        <div class="col-md-10">
          <%= f.text_area :body, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-1 col-md-11">
          <%= f.submit class: "btn btn-primary btn-lg pull-right" %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h3 class="text-center">Editing an Article</h3>

<%= render 'posts/form' %>

app/views/posts/index.html.erb
<%= link_to 'New Post', new_post_path, class: "btn btn-default btn-lg", id: "new-article-btn" %>


<% if @posts.empty? %>
  <h1 id="no-articles">No Articles Created</h1>
<% else %>
  <% @posts.each do |post| %>
    <div class="well well-lg">
      <div class="post-id">
        <%= link_to post.id%>
      </div>
      <div class="article-title">
        <%= link_to post.title, post_path(post) %>
      </div>
      <div class="article-body">
        <%= truncate(post.body, length: 500) %>
      </div>

    </div>

  <% end %>
<% end %>

app/views/posts/new.html.erb
<h3 class="text-center">Adding New Article</h3>

<%= render 'posts/form' %>

app/views/posts/show.html.erb
<article class="detail-article">
  <h1 class="article-detail-title"><%= @post.title %></h1>

  <div class="glyphicon glyphicon-calendar" id="article-date">
    <%= @post.created_at.strftime("%b %d %Y") %>
  </div>

  <div class="article-body">
    <%= @post.body %>
  </div>

  <div class="edit-delete">
    <%= link_to "Edit Article", edit_post_path(@post), class: "btn btn-primary btn-lg btn-space" %>
    <%= link_to "Delete Article", post_path(@post), method: :delete,
                data: {confirm: "Are you sure you want to delete article?"},
                class: "btn btn-primary btn-lg btn-space" %>
  </div>
</article>
<hr>
<div class="col-md-12">
  <%= form_for [@post, @comment], remote: true,
               :html => {class: "form-horizontal", role: "form"} do |f| %>
    <% if @comment.errors.any? %>
      <div class="panel panel-danger col-md-offset-1">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(@comment.errors.count, "error") %>
            prohibited this comment rom being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% @comment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>

    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :body, 'New Post' %>
      </div>
      <div class="col-md-10">
        <%= f.text_area :body, rows: 10, class: 'form-control', placeholder: 'Your comment' %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label col-md-offset-2 col-md-10">
        <%= f.submit "Add Comment", class: "btn btn-primary btn-lg pull-right" %>
      </div>
    </div>
  <% end %>
</div>
<div class="col-md-12">
  <header>
    <h2>Comments</h2>
  </header>

  <div class="col-md-10">
    <% if @post.comments.any? %>
      <div id="messages">
        <% (@comments).each do |comment| %>
          <div class="comment-body">
            <%= comment.body %>
          </div>
          <div class="comment-owner">
          </div>
          <hr>
        <% end %>
      </div>
    <% else %>
      There are no comments to show.
    <% end %>
  </div>
</div>